# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ae68b4d4b263b2101dd31d559163fb22182cafc1d3ce741e2a02bfd98778bcc93f8e5d86c479e416e5922851a8721a23ac6ad238c30d28cc4dedaac1d1d1eaa

test:
  secret_key_base: cbf3fd9a1c863a760b7001ae44a962da6af7954f21ab3c86b348c43f89bff62c09c7aef7fccc8cd882566b92f61e2be0e24221402af7c5984f535ae77116fa10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
